apiVersion: apps/v1
kind: Deployment
metadata:
  name: deploymnt
  labels:
    app: roboshop
    tier: frontend
spec:
  # modify replicas according to your case
  replicas: {{ .Values.deployment.replicas }}
  selector:
    matchLabels:
      component: nginx-component
      purpose: practice
      environment: dev
  template:
    metadata:
      labels:
        component: nginx-component
        purpose: practice
        environment: dev
    spec:
      containers:
      - name: nginxdele
        image: nginx:{{ .Values.deployment.appVersion }}

       