apiVersion: v1
kind: Service
metadata:
  name: nginx-service
spec:
  type: LoadBalancer
  selector:
    component: nginx-component
    purpose: practice
    environment: dev
  ports:
    - port: 80
      targetPort: 80
      protocol: TCP
      name: name-of-service-port